name: build and run unit tests
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
    steps:
    - name: Install Go
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        # renovate: datasource=golang-version depName=go
        go-version: 1.20.5

    - name: Checkout code
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      with:
        path: src/little-vm-helper

    - name: Build and run Go tests
      run: |
        cd src/little-vm-helper
        make
